#!/bin/bash

SUBDIR="dominator-installer-$(git describe --abbrev=0)/"
INST="/tmp/${SUBDIR}"
mkdir -p "${INST}.install/libs/"
echo "Adding libs"
cp "/usr/lib/libNewton.so" "/usr/lib/libfmodex.so" "/usr/lib/libQtGui.so.4" "/usr/lib/libQtOpenGL.so.4" "/usr/lib/libQtCore.so.4" "/usr/lib/libQtDBus.so.4" "/usr/lib/libQtXml.so.4" "${INST}.install/libs/"
echo "Adding runtime"
cp "./Release/dominator" "${INST}.install/"
echo "Adding data"
cp -r "./Release/data" "${INST}.install/"
echo "Adding licenses"
cp -r "./licenses" "${INST}.install/"
cp "./LICENSE" "./README" "${INST}.install/"
echo "Adding installer"
cp "./install.sh" "${INST}"
echo "Compressing"
FN="$(readlink -f "dominator-$(git describe --abbrev=0).tar.gz")"
cd "/tmp/"
tar -c -z -f "${FN}" "${SUBDIR}"
echo "Done. Cleaning up."
rm -rf "${INST}"
